[package]
name = "zed-extension-azure-mcp"
version = "1.0.0"
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
env = "1.0.1"
serde = "1.0"
schemars = "0.8"
zed_extension_api = "0.5.0"
